apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: azurebusnosecrets
  namespace: default
spec:
  type: bindings.azure.servicebusqueues
  version: v1
  metadata:
  - name: connectionString
    secretKeyRef:
      name: servicebusConnectionString
      key: servicebusConnectionString
  - name: queueName
    value: testqueue
  - name: ttlInSeconds
    value: 60
auth:
  secretStore: azurekeyvault